### ISSUE TITLE
certificado PKCS#7 em formato .pfx

### ISSUE THREAD

**Issue by souza-17** [vitorccs/bradesco-api-php#11]
Como faço para gerar esse certificado, estou com duvidas sobre o mesmo.

**Comment by ghost** [comment]
@souza-17 são certificados comuns para as empresas, se procurar no Google há várias que fornecem esse serviço, apenas atente-se abaixo ao tipo. Verifique também as instruções no manual do Bradesco:
https://github.com/vitorccs/bradesco-api-php/files/2332693/Manual_Registro_de_Boleto_Bancario_Online_Dez17.pdf

Página 5, capítulo 5.1:
O cliente pode adquirir o certificado ICP-BRASIL, preferencialmente do tipo A1 e A3 podendo ser e-CNPJ ou e-CPF. As informações para adquiri-lo estão no site http://www.iti.gov.br/icp-
brasil/estrutura

Você precisar entrar em contato com o gerente do seu banco para ele autorizar o uso da API para a conta-corrente da sua empresa, e ele pode lhe ajudar a guiar os próximos passos.
