### ISSUE TITLE
Manual Técnico (versão 2.2)

### ISSUE THREAD

**Issue by fernandolcardoso** [vitorccs/bradesco-api-php#12]
Olá @vitorccs,

Compartilho o manual atualizado do Bradesco

[4008-524-0883-01_Manual_Tecnico_Layout_Registro_Online_Boleto.pdf](https://github.com/vitorccs/bradesco-api-php/files/4204357/4008-524-0883-01_Manual_Tecnico_Layout_Registro_Online_Boleto.pdf)

**Comment by vitorccs** [comment]
@fernandolcardoso Obrigado por avisar e pelo envio!

Aproveitei da oportunidade para entrar em contato com o canal de atendimento que consta no final do manual (atendimentoregistroonline@7comm.com.br) e solicitei se eles poderiam me enviar a última versão. 

Eles me responderam há instantes atrás e já atualizei o link do Readme
https://github.com/vitorccs/bradesco-api-php/blob/master/README.md
