### ISSUE TITLE
Definição do ambiente

### ISSUE THREAD

**Issue by lucashegomes** [vitorccs/bradesco-api-php#13]
Setar o parâmetro **BRADESCO_SANDBOX** como false não está sendo suficiente para direcionar para o ambiente de produção, pois o **static::$defIsSandbox** é true por padrão, setando sempre a URL de homologação. Como não me importo de informar o parâmetro **BRADESCO_SANDBOX**, contornei a situação desta maneira:

![image](https://user-images.githubusercontent.com/22087562/88973071-ed7f0380-d28c-11ea-879e-5c2e30e3013d.png)

**Comment by ghost** [comment]
@lucashegomes sim, bom ponto.

Verifiquei que `getenv` retorna FALSE caso a variável não foi definida, o que pode confundir com a escolha do usuário, conforme você fez.

Acho que o laço IF onde destactou, sendo movido para dentro do 1o laço, imediatamente após a linha de obter valor do getenv para ser exato, resolveria. 

Desta maneira, acho que o problema seria corrigido sem impactar nenhum dos modos possíveis de definir os parâmetros: seja por variável de ambioente ou por instanciação do objetivo. E poderíamos lançar uma nova release sem medo de quebrar porquem já utiliza.

**Comment by vitorccs** [comment]
@lucashegomes Obrigado por avisar. Corrigido na PR #15 e disponível na nova versão v1.5.0.

Vou documentar para no caso de outras pessoas desejarem avaliar possíveis impactos:

A falha ocorria especificamente ao passar valor booleano `false` para o parâmetro `BRADESCO_SANDBOX` e no "modo array"
```php
\BradescoApi\Http\Bradesco::setParams([
    'BRADESCO_SANDBOX' => false // antes da PR, era ignorado e recebia valor padrão 'true'
]);
```

Em todos os demais casos, esta falha não ocorria:
* Caso o  parâmetro fosse omitido
* Caso o valor fosse passado como string `"false"`
* Caso fosse definido o valor booleano `true`
* Caso o parâmetro tivesse sido definido por "variável de ambiente".

**Comment by lucashegomes** [comment]
Grato pela tratativa. Bom trabalho!

**Comment by lucashegomes** [comment]
@vitorccs uma questão: no seu commit você colocou o if === false dentro do if === null, porém não vai entrar nele já que false é diferente (!==) de  null

![image](https://user-images.githubusercontent.com/22087562/90051389-ff5d9f00-dcad-11ea-8055-7bed9e0cb0e4.png)

**Comment by vitorccs** [comment]
@lucashegomes opa, indo direto a resposta: existe uma situação onde getnv (linha imediatamente acima) pode retornar FALSE: quando o parâmetro não foi enviado. É o comportamento nativo dessa função PHP.

Aqui tem uma explicação mais detalhada:
![screenshot-github com-2020 08 12-15_18_54](https://user-images.githubusercontent.com/9891961/90053529-033ef080-dcb1-11ea-9c91-c3af5d2c63a0.png)

para fazer os testes antes de publicar eu testei as 8 maneiras possíveis (4 de modo env + 4 de modo array)

```php
error_reporting(E_ALL);
ini_set('display_errors', 1);

require __DIR__ . '/vendor/autoload.php';

putenv('BRADESCO_SANDBOX=true'); // getenv retorna como string "true"
putenv('BRADESCO_SANDBOX=false'); // getenv retorna como string "false"
putenv('BRADESCO_SANDBOX='); // getenv retorna como FALSE
// (não passar qualquer parâmetro) getenv retorna como FALSE

Bradesco::setParams([
        'BRADESCO_SANDBOX' => true
]);
Bradesco::setParams([
        'BRADESCO_SANDBOX' => false
]);
Bradesco::setParams([
        'BRADESCO_SANDBOX' => null
]);
Bradesco::setParams([]);

// para cada cenário acima, eu testei como o método tratava 
var_dump(Bradesco::isSandbox());

```
