### ISSUE TITLE
Erro no exemplo

### ISSUE THREAD

**Issue by wcm3web** [vitorccs/bradesco-api-php#14]
Se for utilizar o exemplo substituir
`eecho sprintf("%s (%s)", $e->getMessage(), $e->getErrorCode());`
por
`echo sprintf("%s (%s)", $e->getMessage(), $e->getErrorCode());`

**Comment by vitorccs** [comment]
@wcm3web Obrigado por avisar. Corrigido na PR https://github.com/vitorccs/bradesco-api-php/pull/15.
