### ISSUE TITLE
Erro de Consistencia

### ISSUE THREAD

**Issue by alucardhunter** [vitorccs/bradesco-api-php#16]
Bom dia @vitorccs , estou com um pequeno problema na implementação de seu código, apos realizar as configurações conforme indicado estou recebendo o erro : "message": "ERRO DE CONSISTENCIA:   DADOS INCONSISTENTES - 0840 (6)",

Segue minha configuração:
o CPFCNPJ  raiz da minha empresa possui apenas 8 digitos, tentei de varias formas incluindo o 0 antes e sem ele também para preencher os 9 digitos do campo, sem ele recebo erro de contrato.
Ressaltando também que está em ambiente Sanbox,

`$data = [
            "nuCPFCNPJ" => "1234578",
            "filialCPFCNPJ" => "0001",
            "ctrlCPFCNPJ" => "60",
            "idProduto" => "09",
            "nuNegociacao" => "12340000000123456",
            "nuCliente" => "123456",
            "dtEmissaoTitulo" => "13/08/2020",
            "dtVencimentoTitulo" => "13/08/2020",
            "vlNominalTitulo" => "100",
            "cdEspecieTitulo" => "04",
            "nomePagador" => "Cliente Teste",
            "logradouroPagador" => "Rua Teste",
            "nuLogradouroPagador" => "90",
            "complementoLogradouroPagador" => "",
            "cepPagador" => "12345",
            "complementoCepPagador" => "500",
            "bairroPagador" => "Bairro Teste",
            "municipioPagador" => "Teste",
            "ufPagador" => "SP",
            "cdIndCpfcnpjPagador" => "1",
            "nuCpfcnpjPagador" => "23549435260981",
          ];`

**Comment by vitorccs** [comment]
@alucardhunter pelo que me lembro de trabalhar em ambiente sandbox, os dados precisam ser o mais próximos possíveis da realidade - é bom evitar dados aleatórios/fake. A única coisa que é admissível ser fake é a numeração sequencial do boleto.

Por exemplo, vejo que o nuCPFCNPJ não passaria por uma regra de validação de CPF/CNPJ. Precisa ser ao menos um que passe pela regra de validação (busque por gerador de CPF on-line na internet)

Todos os dados da empresa emissora do boleto precisam também ser reais para que eles possam localizar corretamente sua conta do outro lado, inclusive o certificado.

=> Ou seja, assegure que os dados estejam corretos, e que já iniciou uma negociação com o Bradesco, que eles receberam todos os dados de sua empresa, e deram OK para você iniciar o sandbox.

**Comment by alucardhunter** [comment]
@vitorccs todos os dados relacionados a empresa e o certificado usado no meu código são dados reais, coloquei só por informação mesmo na issue, apenas os dados do pagador são dados ficticios. E o pessoal do Bradesco também ja liberou nosso contrato.

**Comment by vitorccs** [comment]
@alucardhunter algo deve estar escapando, infelizmente a validação de dados da API não indica o campo e o erro específico. No manual do Bradesco (coloquei o link dele na página inicial deste repositório), tem o capítulo 9.3 que indica todos os campos possíveis para você verificar.

_9.3 Dados Inconsistentes –Possíveis Retornos
O retorno 06 –Dados Inconsistentes pode compreender as seguintes mensagens:_

**Comment by ghost** [comment]
@alucardhunter outra possibilidade, é dar uma olhada aqui https://github.com/vitorccs/bradesco-api-php/blob/master/src/BankSlip.php

Ao invés de chamar para Registrar o Boleto
```php
$bankSlip = \BradescoApi\BankSlip::create($arrayDados);
```

Você pode conferir seu array antes e após o ajuste - que essa biblioteca faz automático.
```php
$arrayDadosAposAjuste = \BradescoApi\Helpers\Fixer::fixAll($arrayDados);
print_r($arrayDadosAposAjuste);
```

**Comment by alucardhunter** [comment]
@vitorccs  Entendi, eu vou olhar aqui, essa sua biblioteca ta funcionando normalmente para os boletos registrados do bradesco ? Eu estive em contato com o pessoal de desenvolvimento de la, eles me passaram um manual totalmente diferente que em questão realizava o registro via arquivo de remessa.

**Comment by vitorccs** [comment]
@vitorccs sim, funciona normalmente (rs). O benefício da API é o registro em tempo real por uma tecnologia moderna de REST/JSON.

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf

**Comment by marquesjuniorpalmas** [comment]
Boa Tarde,

Hoje comecei a integração e estou com problemas de Não foi possível registrar o boleto. ERRO DE CONSISTENCIA:   DADOS INCONSISTENTES - 0840 (6)

Alguém já teve esse problema?

**Comment by vitorccs** [comment]
@marquesjuniorpalmas envia os dados que você está tentando registrar, siga os passos que mencionei acima https://github.com/vitorccs/bradesco-api-php/issues/16#issuecomment-673644672
