### ISSUE TITLE
Acesso a API

### ISSUE THREAD

**Issue by marconneves** [vitorccs/bradesco-api-php#17]
Pessoal, estou tentando achar no bradesco como acessar o token e tudo mais relacionado a esta api, alguem poderia me ajudar, um guia básico, ou só um link ehheh, obrigado desde então!

**Comment by vitorccs** [comment]
@marconwillian você precisa falar com o gerente do seu banco que deseja usar a API de Registro Online de Boletos do Bradesco. Ele vai lhe colocar em contato com uma equipe para fazer o cadastro da sua empresa. Você vai precisar de um arquivo de certificado da sua empresa e enviar a está equipe. Somente aí poderá acessar a API, mesmo que em ambiente Sandbox.

**Comment by marconneves** [comment]
@vitorccs Outra duvida se não me emporta, sabe se eles tem um postback?  Para saber quando o boleto é compensado?

**Comment by vitorccs** [comment]
@marconwillian negativo, somente possuem para registro do boleto, não possuem endpoint para alteraçao ou webhook para receber retorno. para os 2 últimos cenários, infelizmente ainda é pelo método de arquivo remessa e retorno.

**Comment by marconneves** [comment]
Vlw ai pelo apoio, vou dar uma pesquisada, vlw
