### ISSUE TITLE
Gerar documento PDF

### ISSUE THREAD

**Issue by alisonjr** [vitorccs/bradesco-api-php#23]
Eu estou utilizando a biblioteca, e tenho o retorno do banco com o código de barras, e os outros dados. Porém eu gostaria de ter a ficha de pagamento (pdf do boleto). É possível gerar com essa lib? Caso sim? como proceder? Caso não, como gerar? oq ue vocês estão utilizando para gerar o documento?

**Comment by vitorccs** [comment]
@alisonjr  Essa biblioteca é responsável apenas por registrar o Boleto.

Há 2 bibliotecas especializadas em gerar boletos PHP:
https://github.com/openboleto/openboleto
https://boletophp.com.br

Os dados que elas precisam para gerar os boletos é levemente diferente mas naturalmente chegam ao mesmo resultado (código de barras e linha digitável será idêntico com a resposta da API Bradesco de Registro)
