### ISSUE TITLE
Endpoint e Baixa

### ISSUE THREAD

**Issue by mlizander** [vitorccs/bradesco-api-php#28]
Olhando sua API, notei duas coisas:
- O endpoint que está na sua API, é o https://cobranca.bradesconetempresa.b.br/ibpjregistrotitulows/registrotitulo para produção e https://cobranca.bradesconetempresa.b.br/ibpjregistrotitulows/registrotitulohomologacao, porém, no manual que me foi enviado pelo Bradesco (Versão 1 de novembro de 2022), o endereço é único (https://openapi.bradesco.com.br/v1/boleto/registrarBoleto), com a diferenciação em um campo se "1" produção, se "2" homologação... E esse campo existe nos seus dados fixos do boleto, então não entendi se o endereço para o registro mudou.
- Sua SDK não possui o endpoint para solicitação de baixa (cancelamento do boleto) e alteração de dados do boleto, certo?

**Comment by vitorccs** [comment]
@mlizander por favor, anexe a documentação que você recebeu do Bradesco para verificarmos se trata-se da mesma API. Assim ajudaremos mais pessoas que passam por aqui com a mesma dúvida.

**Comment by mlizander** [comment]
OK... segue anexo
[Manual API de Cobrança_v1.pdf](https://github.com/user-attachments/files/17279062/Manual.API.de.Cobranca_v1.pdf)

**Comment by mlizander** [comment]
É a API de registro de boletos, porém ela também tem a questão da baixa (solicitação por parte do emissor) e alteração de dados... e notei que o endpoint é diferente

**Comment by mlizander** [comment]
Pelo menos todo o resto parece bater... estruturas, nomes dos campos, etc... no que tangue ao registro de boletos...

**Comment by vitorccs** [comment]
@mlizander ah com certeza são APIs diferentes. A API usada neste SDK é dedicada apenas a fazer registro de boleto. A que você anexou aqui, é mais ampla, tem mais funções além do registro, contendo alteração, baixa, etc.

Obs: Uma pena o Bradesco não ter um portal de desenvolvedores com a documentação fácil para ser consultada ou baixada, sendo necessário a gente ficar solicitando. E também eles já não reunirem as SDKs ou até criarem as oficiais deles. Vemos os anos passando e quase zero evolução nesses quesitos.

**Comment by mlizander** [comment]
É... então não vou conseguir usar o seu SDK... muito obrigado...
