### ISSUE TITLE
Erro certificado.

### ISSUE THREAD

**Issue by matheusc06** [vitorccs/bradesco-api-php#7]
recebo esse erro ao tentar rodar o codigo.
Erro Certificado / Formatacao dos campos da mensagem invalida [0x00d30003] (810)

Alguém sabe pq? n consegui identificar o problema, estou usando o mesmo código do exemplo.

**Comment by ghost** [comment]
@matheusc06 

2 passos a verificar:
1) Mesmo em ambiente sandbox, creio ser necessário entrar com os dados de sua carteira no Bradesco: 
```php
[
  "nuCPFCNPJ"         => "123456789",
  "filialCPFCNPJ"     => "0001",
  "ctrlCPFCNPJ"       => "39",
  "idProduto"         => "09",
  "nuNegociacao"      => "123400000001234567",
  "cdEspecieTitulo"   => "04"
]
```

2) É verificar se o arquivo possui acesso de leitura para o usuário do Apache e se o caminho dele está correto na variável `BRADESCO_CERT_PATH`

**Comment by ghost** [comment]
@matheusc06 por favor fechar a issue caso tenha solucionado

**Comment by satara** [comment]
Também estou recebendo este erro e os dados parecem ok e certificado tem permissão de leitura. O código é compatível com a última versão do Bradesco? No manual deles a URL de homologação é https://proxy.api.prebanco.com.br e no seu código está 'https://cobranca.bradesconetempresa.b.br/'.

**Comment by vitorccs** [comment]
@satara sim, a URL está correta e transancionado normalmente. Por favor, envie o manual do Brasdesco que você possui

**Comment by satara** [comment]
Vitor, obrigado pela resposta. Envio o manual anexo e os dados já tratados pelo seu código abaixo (só retirei o cpf):
Array ( [cdBanco] => 237 [cdTipoAcesso] => 2 [tpRegistro] => 1 [cdTipoContrato] => 48 [clubBanco] => 2269651 [tpVencimento] => 0 [nuSequenciaContrato] => 0 [eNuSequenciaContrato] => 0 [cdProduto] => 0 [nuTitulo] => 0 [tpProtestoAutomaticoNegativacao] => 0 [prazoProtestoAutomaticoNegativacao] => 0 [controleParticipante] => [cdPagamentoParcial] => [qtdePagamentoParcial] => 0 [percentualJuros] => 0 [vlJuros] => 0 [qtdeDiasJuros] => 0 [percentualMulta] => 0 [vlMulta] => 0 [qtdeDiasMulta] => 0 [percentualDesconto1] => 0 [vlDesconto1] => 0 [dataLimiteDesconto1] => [percentualDesconto2] => 0 [vlDesconto2] => 0 [dataLimiteDesconto2] => [percentualDesconto3] => 0 [vlDesconto3] => 0 [dataLimiteDesconto3] => [prazoBonificacao] => 0 [percentualBonificacao] => 0 [vlBonificacao] => 0 [dtLimiteBonificacao] => [vlAbatimento] => 0 [vlIOF] => 0 [endEletronicoPagador] => [nomeSacadorAvalista] => [logradouroSacadorAvalista] => [nuLogradouroSacadorAvalista] => 0 [complementoLogradouroSacadorAvalista] => [cepSacadorAvalista] => 0 [complementoCepSacadorAvalista] => 0 [bairroSacadorAvalista] => [municipioSacadorAvalista] => [ufSacadorAvalista] => [cdIndCpfcnpjSacadorAvalista] => 0 [nuCpfcnpjSacadorAvalista] => 00000000000000 [endEletronicoSacadorAvalista] => [nuCPFCNPJ] => 038052160 [filialCPFCNPJ] => 0057 [ctrlCPFCNPJ] => 01 [idProduto] => 09 [nuNegociacao] => 399500000000075557 [nuCliente] => 0000123456 [dtEmissaoTitulo] => 27.11.2023 [dtVencimentoTitulo] => 30.11.2023 [vlNominalTitulo] => 10000 [cdEspecieTitulo] => 04 [nomePagador] => Cliente Teste [logradouroPagador] => Rua Jardim Botanico [nuLogradouroPagador] => 90 [complementoLogradouroPagador] => 102 [cepPagador] => 22460 [complementoCepPagador] => 000 [bairroPagador] => Jardim Botanico [municipioPagador] => Rio de Janeiro [ufPagador] => RJ [cdIndCpfcnpjPagador] => 1 [nuCpfcnpjPagador] => 0000RETIRADO )
[api_registro_cobranca_registro on line_boletos.pdf](https://github.com/vitorccs/bradesco-api-php/files/13479434/api_registro_cobranca_registro.on.line_boletos.pdf)
[manual do desenvolvedor v_3.3.pdf](https://github.com/vitorccs/bradesco-api-php/files/13479435/manual.do.desenvolvedor.v_3.3.pdf)

**Comment by satara** [comment]
Eu enviei dois arquivos .pem para o banco registrar na homologação, depois converti em um único arquivo .pfx, pode ser esse o problema?

**Comment by vitorccs** [comment]
@satara acredito que possa ser algum erro no .pfx sim.

Primeiramente, você precisa ter certeza que está usando um certificado do tipo A1 (ele geralmente vem em formato PFX ou P12).  O formato varia de empresa certificadora, e talvez elas possam ter a opção de você escolher o formato na hora de fazer o download, ou tenham algum manual instruindo a conversão

Não cheguei a testar, mas parece que é possível converter de P12 para PFX, por exemplo:
https://www.webdanfe.com.br/certificados/manual/Manual-exportacao-do-certificado-A1-para-pfx.php

=== exemplo de como está o .pfx aqui:

Private RSA Key
Strength: 2048 bits

Identity: NOME_EMPRESA
Verified by: AC VALID RFB

Identity: Autoridade Certificadora Raiz Brasileira v2
Verified by: Autoridade Certificadora Raiz Brasileira v2

Identity: AC Secretaria da Receita Federal do Brasil v3
Verified by: Autoridade Certificadora Raiz Brasileira v2

Identity: AC VALID RFB
Verified by: AC Secretaria da Receita Federal do Brasil v3

**Comment by satara** [comment]
Eu gerei um certificado no meu computador pois pelo manual era suficiente para homologação, mas vou ver se a empresa gera um a partir do eCNPJ. Esse meu não deveria ser problema pois o banco aceitou.
