### ISSUE TITLE
Impressão Boleto

### ISSUE THREAD

**Issue by sampiron** [vitorccs/bradesco-api-php#8]
Bom Dia Vitor,
Primeiramente parabenizar pela API, muito boa e pratica para usar.
Uma sugestão seria colocar um Layout do Boleto para poder imprimir ele assim que retornar a resposta do webservice.

Obrigado.

**Comment by ghost** [comment]
Olá @sampiron obrigado pelo feedback

Irei analisar o esforço envolvido pois são muitas as variáveis envolvidas para gerar o boleto em PDF.

A princípio, recomendaria bibliotecas PHP dedicadas a este tópico. Para o banco Bradesco consta como "homologado" a emissão e geração em PDF.

Emissão:
https://github.com/openboleto/openboleto

Geração em PDF:
https://github.com/QuilhaSoft/JasperPHP-OpenBoleto
